# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xf4\x01\n\x12TransactionPayload\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x1d\n\x15hashed_source_account\x18\x02 \x01(\t\x12\x1d\n\x15hashed_target_account\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x10\n\x08latitude\x18\x06 \x01(\x01\x12\x11\n\tlongitude\x18\x07 \x01(\x01\x12\x15\n\roff_ramp_type\x18\x08 \x01(\t\x12\x11\n\thop_count\x18\t \x01(\x05\x12\x16\n\x0evelocity_score\x18\n \x01(\x01\"\x88\x01\n\x0eRiskAssessment\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x12\x10\n\x08h3_index\x18\x03 \x01(\t\x12\x1b\n\x13requires_debit_hold\x18\x04 \x01(\x08\x12\x1b\n\x13target_jurisdiction\x18\x05 \x01(\t2_\n\x13GnnInferenceService\x12H\n\x0c\x45valuateRisk\x12\x1d.telemetry.TransactionPayload\x1a\x19.telemetry.RiskAssessmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONPAYLOAD']._serialized_start=31
  _globals['_TRANSACTIONPAYLOAD']._serialized_end=275
  _globals['_RISKASSESSMENT']._serialized_start=278
  _globals['_RISKASSESSMENT']._serialized_end=414
  _globals['_GNNINFERENCESERVICE']._serialized_start=416
  _globals['_GNNINFERENCESERVICE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
