# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GnnInferenceServiceStub:
    """The gRPC service definition connecting Rust to Python
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRisk = channel.unary_unary(
                '/telemetry.GnnInferenceService/EvaluateRisk',
                request_serializer=telemetry__pb2.TransactionPayload.SerializeToString,
                response_deserializer=telemetry__pb2.RiskAssessment.FromString,
                _registered_method=True)


class GnnInferenceServiceServicer:
    """The gRPC service definition connecting Rust to Python
    """

    def EvaluateRisk(self, request, context):
        """Receives a single anonymized transaction and returns a risk assessment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GnnInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRisk,
                    request_deserializer=telemetry__pb2.TransactionPayload.FromString,
                    response_serializer=telemetry__pb2.RiskAssessment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.GnnInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.GnnInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GnnInferenceService:
    """The gRPC service definition connecting Rust to Python
    """

    @staticmethod
    def EvaluateRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.GnnInferenceService/EvaluateRisk',
            telemetry__pb2.TransactionPayload.SerializeToString,
            telemetry__pb2.RiskAssessment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
